HOSTS:
  docker-centos6-66-msm:
    roles:
      - docker_container
      - master
    platform: el-6-x86_64
    image: centos:6.6-msm
    hypervisor: docker
CONFIG:
  # When you need to inspect the commands being used, you can use log_level
  # log_level: verbose
  quite: true
  type: foss
  masterless: true
