HOSTS:
  default:
    platform: el-6-x86_64
    image: centos:6.6-msm
    hypervisor: docker
    docker_container_name: centos6.6-msm
CONFIG:
  log_level: warn
  quite: true
  type: foss
  masterless: true
