fixtures:
  # repositories:
  #   requirement:
  #     repo: 'https://github.com/MSMFG/puppet-requirement'
  #     ref: '0.0.10'
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.6.0'
  symlinks:
    brownbag: '#{source_dir}'
