AllCops:
  DefaultFormatter: progress
  AutoCorrect: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

# Cyclomatic complexity is a measure of source code complexity.
Metrics/CyclomaticComplexity:
  Max: 10

# Assignment Branch Condition is strictly a software size metric, although it
# has often been misconstrued as a complexity metric.
Metrics/AbcSize:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 180

Metrics/BlockLength:
  Max: 40

Style/MultilineHashBraceLayout:
  EnforcedStyle: symmetrical

Style/MultilineMethodCallBraceLayout:
  EnforcedStyle: symmetrical

Style/MultilineArrayBraceLayout:
  EnforcedStyle: symmetrical
