gemspec
source 'https://rubygems.org' do
  group :docs do
    gem 'puppet-strings'
  end

  group :development do
    gem 'bundler', '~> 1.11'
    gem 'coveralls'
    gem 'hiera'
    gem 'hiera-puppet-helper'
    gem 'metadata-json-lint'
    gem 'pry'
    gem 'puppet', '< 4'
    gem 'puppetlabs_spec_helper' # This requires/installs a lot of goodies
    gem 'rake', '~> 10.0'
    gem 'rubocop'
    gem 'ruby-augeas'
    gem 'safe_yaml' # This is required to make puppet 3 to work with ruby 2.2.5
    gem 'sensu-plugin'
    gem 'serverspec'
    gem 'wirble'
  end

  group :acceptance do
    gem 'beaker'
    gem 'beaker-facter'
    gem 'beaker-hiera'
    gem 'beaker-rspec'
    gem 'minitest'
  end
end
