require 'bundler/gem_tasks'
require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-strings/tasks'
require 'rake/clean'

# Instead of write a `begin` block, I prefer to write a function (taking
# advantage of the implicit `begin` block).

# Builds the docker image for beaker, if it's not available.
def docker_build
  sh 'docker images | grep --quiet "^centos *6.6-msm"', verbose: false
rescue RuntimeError
  sh 'docker build --tag centos:6.6-msm .', verbose: false
end

# Deletes the docker image for beaker, ignoring any error
def docker_rmi
  sh 'docker rmi --force centos:6.6-msm', verbose: false
rescue RuntimeError => error
  puts error.message
end

# Runs brownbag container for serverspec
def docker_run
  sh 'docker ps | grep --word-regexp --quiet brownbag', verbose: false
rescue RuntimeError
  command = "/bin/bash -c 'while true ; do sleep 100 ; done'"
  sh "docker run --name brownbag --detach centos:6.6 #{command}", verbose: false
end

# Shuts down the brwonbag container
def docker_rm
  sh 'docker rm --force brownbag', verbose: false
rescue RuntimeError => error
  puts error.message
end

desc 'Build the docker image for beaker'
task(:docker_build) { docker_build }

desc 'Deleted the docker image created for beaker'
task(:docker_rmi) { docker_rmi }

desc 'Runs the brownbag container'
task(:docker_run) { docker_run }

desc 'Shuts down the brownbag container'
task(:docker_rm) { docker_rm }

# `:clean` task is supposed to clean intermediate/temporary files
# `CLEAN` array tells which files to remove on `clean` task.
CLEAN.include %w(.yardoc coverage log junit)

# `:clobber` task is uspposed to clean final products. Requires `:clean` task.
# `CLOBBER` array tells which files to remove on `clobber` task.
CLOBBER.include %(doc pkg)

task clean: [:docker_rm, :docker_rmi]

# You normally don't need to re-define `:spec_standalone`, but this is a
# special all-in-one project
Rake::Task[:spec_standalone].clear
RSpec::Core::RakeTask.new(:spec_standalone) do |rspec|
  specs = 'classes,defines,functions,types,rspec_brownbag,serverspec'
  rspec.pattern = "spec/{#{specs}}/**/*_spec.rb"
  rspec.ruby_opts = '-W0'
  rspec.verbose = false
end

# Defining few sane requirements for the spec task. To me, it doesn't make any
# sense to run specs if validation, style checking and documentation fail.
task spec: [:validate, :lint, :rubocop, :'strings:generate', :docker_run]

# Again, doesn't make any sense to run acceptance specs if standard specs fail.
desc 'Run the acceptance specs'
RSpec::Core::RakeTask.new acceptance: [:spec, :docker_build] do |rspec|
  rspec.pattern = 'spec/acceptance/**/*_spec.rb'
  rspec.ruby_opts = '-W0'
  rspec.verbose = false
end
