require 'bundler/gem_tasks'
require 'yard'
require 'rake/clean'
require 'rake/file_utils'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

# Tells which files to remove on clean task.
CLEAN.include(['.yardoc', 'doc', 'coverage'])

RuboCop::RakeTask.new

YARD::Rake::YardocTask.new

def docker_build
  sh 'docker images | grep "^centos *6.6-msm"'
rescue RuntimeError
  sh 'docker build --tag centos:6.6-msm .'
end

task(:docker_build) { docker_build }

RSpec::Core::RakeTask.new spec: [:rubocop, :yard] do |t|
  t.rspec_opts = '--exclude spec/acceptance/**/*_spec.rb'
end

RSpec::Core::RakeTask.new acceptance: [:rubocop, :yard, :docker_build] do |t|
  t.rspec_opts = '--pattern spec/acceptance/**/*_spec.rb'
end

# Tasks to run if rake command is called without arguments.
task build: [:clean, :spec]
